on:
    push:
        branches: [main]
    schedule:
        - cron: '0 0 * * *' # Runs every day at midnight UTC

jobs:
    cron_job:
        name: Scheduled Job
        runs-on: ubuntu-latest
        steps:
            - name: Check the deployed service
              uses: jtalk/url-health-check-action@v4
              with:
                url: 'https://example.com' # Replace with your service URL
                follow-redirect: false
                max-attempts: 3
                retry-delay: 10

              
        
